appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: RBhsC+IayRdQutaIVDvF8E/ZgeNPJmyNtBNqnG1AD9ZIlU18MivKnHINGDmRXvHNZThnX8JXVtVYyi4UfkMTLRNJzF11stpqqDraqOoaHLpCCU/LBGGvgTvOK0BS3/s8y1jEQl9hyyvLxbO/sPFoQrSB9Xv/BX1X4kmYd0cduwuRCQa+xl4kt01dqTIGmntfOsOCbAWGVsuBvZ54qjd2pVGdXnp6DhTZhoeLDkpOM81vj5qRnMNvIgaabKOq1HUiCxDftaMMyoFv+M5/I82Z4xjT3WOAQtAd8LJjCFmq8CiEYI0bolsVHQfzh+5yBKjOXvMx3BiV9Ahc1IIfy5eff9WV/+Lt9tHapYdBsy4QCGUc3OaeNpJZM431WU/0f065pa0SiRi+4keqsAQS2i7QBM67mpFpG4ItjT/PRyDYSQZpar6phaSh1UBDFLN6D25X4fuPb1VLv3CyxoY65KULUdBA5mofR9bCfDC14ooR+b/DSsiiDvdwXvWgZ0UnQhxFZxyd8MZ1HElsY2lLSOcumgIhSzn547KAFChbgBKtEuiztwElT917oBuOxgjUIR+SjIvNXqOdRGa7C98UFZp0db4jO6A0KST+znndtl01ibeNdetE+/1+IPC+pRtjB6YdWlWfWtf+JVPjSTfBpXnfN834PFapsblo4mRIPkpSr2Q=
conda_forge_output_validation: false
